<?php

namespace app\common\controller;

use think\Controller;
use think\Request;

class api extends Controller
{

    protected $request = null;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->request = Request::instance();
        $action = $this->request->action();
        if($action != 'apiLogin'){
            $jwt = $this->request->header('AUTH-TOKEN');
            //TODO
        }
    }

    function result($data = [])
    {
        $data = [
            'error_code' => '0000',
            'error_message' => 'success',
            'data' => $data,
            'server_time' => time(),
        ];

        return [$data, 200, ['Allow-Origin' => '*']];
    }

    function error($error_code, $customMessage = '')
    {
        $message = $customMessage ? $customMessage : $error_code['message'];
        $data = [
            'error_code' => $error_code['code'],
            'error_message' => $message,
            'data' => [],
            'server_time' => time(),
        ];

        return [$data, 200, ['Allow-Origin' => '*']];
    }

}
