<?php

namespace app\api\controller;

use app\common\controller\Api;
use think\Request;
use app\admin\model\WechatUser as User;

class WechatUser extends Api
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function postUserInfo(Request $request)
    {
        $postData = [
            'username' => $request->post('nickname'),
            'useravatarurl' => $request->post('avatarurl'),
        ];

        $msg = [
            'username' => 'require',
            'useravatarurl' => 'require'
        ];

        $result = $this->validate($postData, $msg);

        if ($result !== true) {
            return $this->own_error(40001, '缺少参数');
        }

        $query = new User();
        $query->save($postData, ['id' => $request->user->id]);
        return $this->own_result();
    }
}
