<?php

namespace app\api\controller;

use app\api\helper\TokenHelper;
use app\common\controller\Api;
use app\api\helper\WechatHelper;
use app\admin\model\WechatUser as User;
use think\Request;

class WechatController extends Api
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    function login(Request $request)
    {
        $code = $request->get('code');
        if (empty($code)) {
            return $this->own_error(['code' => 40001], '未接收到参数');
        }

        $appid = config('wechat.appid');
        $secret = config('wechat.secret');
        $ret = WechatHelper::grantOpenID($code, $appid, $secret);

        return $this->own_result($ret);
    }

    function test()
    {
        echo 'test';
    }
}
